# Generated by Django 5.2.3 on 2025-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ideas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('DateOfIdea', models.DateField()),
                ('Photo', models.URLField(max_length=500)),
                ('OwnerID', models.BigIntegerField()),
                ('Status', models.CharField(max_length=500)),
                ('numberOfLikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('school', models.CharField(max_length=500)),
                ('schoolclass', models.CharField(max_length=500)),
            ],
        ),
    ]
